version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      APP_NAME: "Bridge ENS Club"
      APP_ENV: "local"
      APP_KEY: ""
      APP_DEBUG: "true"
      APP_URL: "http://localhost"
      LOG_CHANNEL: "stack"
      LOG_LEVEL: "debug"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: 3308
      DB_DATABASE: "bridgens_db"
      DB_USERNAME: "root"
      DB_PASSWORD: "bridgens@2024"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "bridgens@2024"
      MYSQL_DATABASE: "bridgens_db"

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
